[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/resume"
  to = "/resume.pdf"
  status = 200

[[redirects]]
  from = "/*"
  to = "/404"
  status = 404 